# ===== Basic =====
seed: 67
dataset: cifar100
model: vit

# ===== token mixer =====
attn_head_dim: 32
attn_qkv_bias: true
attn_drop: 0.0
attn_proj_drop: 0.0

# ===== Model =====
img_size: 32
patch_size: 2
embed_dim: 256
depth: 8
mlp_ratio: 4.0
norm_layer: layernorm
act_layer: GELU

drop_rate: 0.0
drop_path: 0.0
add_pos_emb: true
use_layer_scale: true
layer_scale_init_value: 1e-5

# ===== Training =====
epochs: 100
train_batch_size: 128
test_batch_size: 256

learning_rate: 3e-4
weight_decay: 0.05
decay_type: cosine
warmup_epochs: 10
max_grad_norm: 1.0

# ===== Etc =====
num_classes: 100
num_workers: 8
log_interval: 50
fp16: true
data_path: ./data
save_best: true
output_path: ./output/vit/